services:
  postgres:
    image: postgres:16
    container_name: corebank-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - corebank-postgres-data:/var/lib/postgresql/data

volumes:
  corebank-postgres-data:
