spring.application.name=corebank-gateway

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:corebank}
spring.datasource.username=${POSTGRES_USER:corebank}
spring.datasource.password=${POSTGRES_PASSWORD:corebank}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
