spring.application.name=corebank-scheduler

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:corebank}
spring.datasource.username=${POSTGRES_USER:corebank}
spring.datasource.password=${POSTGRES_PASSWORD:corebank}
